<a href="https://colab.research.google.com/github/thecodemancer/study-with-me/blob/main/python/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy arrays

Multidimensional arrays of data.

- They can be one, two, three, four, five and even six dimensional.
- Efficient when performing linear algebra operations.
- element-by-element operations.


In [10]:
 import numpy as np


In [11]:
np.__version__

'1.21.6'

Next, we create a 1D NumPy array to demonstrate its functionality.

In [12]:
a = np.array([1,2,3,4,5,6])

In [13]:
a.shape

(6,)

## One-Dimensional NumPy *Arrays*

Brackets are used to index and cut arrays, as with lists and tuples. The first element of an array is index 0, not 1


In [14]:
a = np.array([1,2,3,4,5,6])

In [15]:
a[0]

1

The notation for subtraction is array[start_position:end_position], where the end position is excluded. For example, array[0:2] will return
the items indexed 0 and 1, not the 0, 1 and 2.

In [16]:
a[0:2]

array([1, 2])

In [17]:
 a[1:3]

array([2, 3])

The last element of an array can be accessed with -1, as is the case with lists and tuples.

In [18]:
a[-1]

6

## 2-D Two-Dimensional NumPy Arrays

2D NumPy arrays are arrays in two dimensions, that is, matrices. They can be defined with a list of lists, where each element of
a nested list is a row.
Next, we define a matrix with two rows and three columns. When we use array.shape, the number of rows and columns is seen in
order.

In [19]:
array = np.array([
 [1,2,3],
 [2,3,4]
])
array.shape

(2, 3)

In [20]:
array

array([[1, 2, 3],
       [2, 3, 4]])

When subtracting indices from 2D arrays, we must define the rows and columns that we want Python to return. The code that
we have below will execute the entire data array because the colon with no indices before and after means "show everything".
When we subtract indices from 2D arrays, the comma is used to separate the values we want to index first into rows and then into
columns. The syntax is array[rows_to_select, columns_to_select]

In [21]:
array[:,:]

array([[1, 2, 3],
       [2, 3, 4]])

Adding 0:1 before the comma tells NumPy to display only row 0, since row 1 is excluded.

In [22]:
array[0:1,:]

array([[1, 2, 3]])

Adding 0:2 after the comma tells NumPy to display only columns 0 and 1, since 2 is excluded

In [23]:
array[:,0:2]


array([[1, 2],
       [2, 3]])

If we put them together, we will get columns 0 and 1 from row 1

In [24]:
array[0:1,0:2]

array([[1, 2]])

## loops

Loops can also be made on NumPy arrays, as we will see next.

In this example we have a 1D NumPy array (6). Since there are six elements and only one dimension, the loop displays them one at a time.

In [26]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [27]:
for i in a:
 print(i)

1
2
3
4
5
6


In this case we have a 2D array (2, 3) so the loop returns two arrays with three elements each.

In [28]:
array = np.array([
 [1,2,3],
 [2,3,4]
])
array.shape


(2, 3)

In [29]:
for i in array:
 print(i)


[1 2 3]
[2 3 4]


The shape attribute returns the number of elements for each array.

Although it is not part of the program, we will explain an example of a loop in an array with three rows and four columns.

If we wanted to pass each of the arrays, we would see that we have three dimensions, so two of them correspond to those
3 by 4 arrays.

In [30]:
 array = np.array([
 [1,2,3,4],
 [2,3,4,4],
 [2,3,4,4]
])
array1 = np.array([
 [5,6,7,4],
 [4,6,9,4],
 [2,3,4,4]
])
tensor = np.array([array, array1])
tensor.shape

(2, 3, 4)

In [31]:
for i in tensor:
 print(i)
 print("-----------------")

[[1 2 3 4]
 [2 3 4 4]
 [2 3 4 4]]
-----------------
[[5 6 7 4]
 [4 6 9 4]
 [2 3 4 4]]
-----------------


## Calculations with arrays

The array class has many built-in math methods, such as .sum(), .min(), .max(), .mean(), .std(), etc. Although not a method
proper to the array class, NumPy has a separate function to calculate the mean: np.median(array_to_find_the_mean).

In [32]:
a = np.array([1,2,3,4])

In [33]:
a.sum()

10

In [34]:
a.min()

1

In [35]:
a.max()

4

In [36]:
a.mean()

2.5

In [37]:
a.std()

1.118033988749895

In [38]:
np.median(a)

2.5

Calculations on arrays can be done element by element, that is, the operation is performed on each element of the array. This
allows you to create concise and efficient code.
find_the_mean).

In [39]:
a

array([1, 2, 3, 4])

In [41]:
a**2

array([ 1,  4,  9, 16])

In [42]:
a+2

array([3, 4, 5, 6])

In [43]:
a-5

array([-4, -3, -2, -1])

In [44]:
a*2

array([2, 4, 6, 8])

In [45]:
a/2

array([0.5, 1. , 1.5, 2. ])

## axis parameter
If we had a multidimensional array like a 2D, we would have to specify in which axis (axis) the calculation will be performed. For example: NumPy
should I calculate the sum of each row or each column?

In [46]:
 array = np.array([
 [1,2,3],
 [2,3,4]
])
array.shape

(2, 3)

When we set axis = 0, we are telling NumPy to add along axis 0, that is, the columns. This can
be strange, since when we look at the shape of the array, we see that it is (2,3) and we expect to receive back two values. Instead of
So, think of NumPy passing along the x-axis and adding each column. Sum “along” the 0-axis.

In [47]:
array.sum(axis = 0)

array([3, 5, 7])

If we set the value of the axis to 1 we get the sum of each row, since it is done along the second axis

In [48]:
array.sum(axis = 1)


array([6, 9])

If we do not give a value to the axis, all the values of the array will be added

In [49]:
array.sum()

15

The axis argument is important in NumPy as it allows us to perform different calculations of rows and columns. We can change sum to any other type of operation that we know of, like mean or max.

In [50]:
array.mean(axis = 0)

array([1.5, 2.5, 3.5])

In [51]:
array.mean(axis = 1)

array([2., 3.])

Note that the results we get are NumPy arrays, which can be further manipulated if necessary.

In [52]:
col_means = array.mean(axis = 0)
col_means[0:2]

array([1.5, 2.5])